global using CSharpFunctionalExtensions;
global using Docflow.Application.Extensions;
global using Docflow.Application.Interfaces;
global using Docflow.Application.Models.DiadocGateway;
global using Docflow.Application.Services;
global using Docflow.Application.Services.Gateways;
global using Docflow.Domain.Models;
global using FastEndpoints;
global using Microsoft.Extensions.Options;
